## Comparing performance with lists



In [1]:
N = 100000


In [17]:
%%time
list1 = list(range(N))
for i in range(N):
    list1[i] = list1[i]* list1[i]


Wall time: 125 ms


In [18]:
%%time
list1 = list(range(N))
list1 = [item * item for item in list1]

Wall time: 32 ms


In [19]:
%%time 
list1 = list(range(N))
list1 = map(lambda x: x*x, list1)

Wall time: 4 ms


In [30]:
%%time
list_sum =0
list1 = list(range(N))
for i in list1:
    list_sum += i

Wall time: 47 ms


In [37]:
%%time
list1 = list(range(N))
list_sum = sum
print(type(list_sum))

<class 'int'>
Wall time: 5 ms


## Numpy


In [1]:
import numpy as np   


In [4]:
arr = np.arange(5) #autogenerate array

In [12]:
arr = np.array([1.0,2,3,4,5]) #list to numpy array

In [5]:
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [13]:
print(arr)

[1. 2. 3. 4. 5.]


In [6]:
arr

array([0, 1, 2, 3, 4])

In [14]:
arr.dtype

dtype('float64')

In [8]:
arr.ndim

1

In [9]:
arr.shape

(5,)

In [10]:
arr.size

5

In [15]:
arr.itemsize

8

In [16]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])

In [17]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr2d.ndim, arr2d.shape, arr2d.size

(2, (2, 3), 6)

In [21]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [22]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d.ndim, arr3d.shape, arr3d.size

(3, (2, 2, 3), 12)

In [24]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
5 * np.ones((3,3,3))

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

In [27]:
np.random.randn(2,3)

array([[ 0.73632011, -0.05211077,  0.58266216],
       [-0.44872546,  2.20575216,  0.78942123]])

In [28]:
np.random.rand(2,3)

array([[0.13998174, 0.82483108, 0.42204108],
       [0.63357367, 0.7588655 , 0.05444214]])

In [31]:
np.random.randint(10,100,(2,3))

array([[16, 83, 41],
       [31, 44, 80]])

In [32]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [38]:
arr = np.array([True, False, True, False, True])

In [39]:
arr.dtype

dtype('bool')

In [41]:
arrstr = np.array(['1.10','2.65','3.18'])

In [42]:
arrstr

array(['1.10', '2.65', '3.18'], dtype='<U4')

In [43]:
arrs = np.array(arrstr, dtype='float')

In [44]:
arrs

array([1.1 , 2.65, 3.18])

In [45]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [46]:
arr3d[0,0,0]

1

In [47]:
arr3d[1,0,2]

9

In [51]:
i=0
j=0
k=2
arr3d[i,j,k]

3

In [52]:
arr3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr3d[:,0,:
]

array([[1, 2, 3],
       [7, 8, 9]])

In [54]:
arr3d[:,:,1] #returns a numpy array with dimension, slice, shape, etc

array([[ 2,  5],
       [ 8, 11]])

In [56]:
arr3d%2==0 #divides all elements by 2

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [57]:
arr3d[arr3d%2==0 ] #rh eturns 1d array with even numbers

array([ 2,  4,  6,  8, 10, 12])

In [60]:
arr3d[(arr3d%2==1) & (arr3d>3) ] #returns all odd numbers greater than 3

array([ 5,  7,  9, 11])

In [63]:
arr_slice = arr3d[:,:,0:2] 

In [64]:
arr_slice[0,0,0] = 20

In [65]:
arr_slice

array([[[20,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [66]:
arr3d
#if array slice value changes, value in the original array also changes

array([[[20,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr_slice1 = np.copy(arr3d[:,:,0:2] )
#using the copy function copies the array and any changes made in the slice does not change the original array

In [69]:
arr_slice1

array([[[20,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [70]:
arr_slice1[0,0,0] = 1

In [71]:
arr_slice1

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [72]:
arr3d

array([[[20,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
a = np.random.randint(0,10,(5))

In [74]:
a

array([4, 3, 7, 2, 9])

In [75]:
indices = [1,2,4]

In [76]:
a[indices]

array([3, 7, 9])

## Numpy Operations


In [86]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [87]:
arr1, arr2

(array([[2, 5, 2, 2],
        [6, 3, 7, 5],
        [7, 4, 5, 9]]),
 array([[3, 8, 5, 1],
        [5, 4, 3, 2],
        [5, 7, 3, 8]]))

In [88]:
arr1+arr2

array([[ 5, 13,  7,  3],
       [11,  7, 10,  7],
       [12, 11,  8, 17]])

In [89]:
arr1-arr2

array([[-1, -3, -3,  1],
       [ 1, -1,  4,  3],
       [ 2, -3,  2,  1]])

In [90]:
arr1*arr2

array([[ 6, 40, 10,  2],
       [30, 12, 21, 10],
       [35, 28, 15, 72]])

In [91]:
arr1/arr2

array([[0.66666667, 0.625     , 0.4       , 2.        ],
       [1.2       , 0.75      , 2.33333333, 2.5       ],
       [1.4       , 0.57142857, 1.66666667, 1.125     ]])

In [92]:
np.exp(arr1)

array([[7.38905610e+00, 1.48413159e+02, 7.38905610e+00, 7.38905610e+00],
       [4.03428793e+02, 2.00855369e+01, 1.09663316e+03, 1.48413159e+02],
       [1.09663316e+03, 5.45981500e+01, 1.48413159e+02, 8.10308393e+03]])

In [94]:
np.log()

array([[2., 5., 2., 2.],
       [6., 3., 7., 5.],
       [7., 4., 5., 9.]])

In [95]:
np.sin(arr1)

array([[ 0.90929743, -0.95892427,  0.90929743,  0.90929743],
       [-0.2794155 ,  0.14112001,  0.6569866 , -0.95892427],
       [ 0.6569866 , -0.7568025 , -0.95892427,  0.41211849]])

In [96]:
np.cos(arr1)

array([[-0.41614684,  0.28366219, -0.41614684, -0.41614684],
       [ 0.96017029, -0.9899925 ,  0.75390225,  0.28366219],
       [ 0.75390225, -0.65364362,  0.28366219, -0.91113026]])

In [97]:
np.sqrt(arr1)

array([[1.41421356, 2.23606798, 1.41421356, 1.41421356],
       [2.44948974, 1.73205081, 2.64575131, 2.23606798],
       [2.64575131, 2.        , 2.23606798, 3.        ]])

In [98]:
np.square(arr1)

array([[ 4, 25,  4,  4],
       [36,  9, 49, 25],
       [49, 16, 25, 81]], dtype=int32)

In [100]:
 arr3 = np.zeros((3,4))

In [101]:
arr_inv = 1/arr3

In [102]:
arr_inv

# 1/0 = inf (infinity)

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [103]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Problem

In [104]:
# 1 x 1 square
# quadrant of radius 1
# estimate area not covered by quadrant


In [2]:
import math

In [108]:
math.pi

3.141592653589793

In [110]:
side = 1
radius = 1
sqaure_area = math.pow(side,2)
quad_area  = 1/4 * math.pi * radius
yellow_area = sqaure_area-quad_area

In [111]:
yellow_area

0.21460183660255172

In [8]:
ndim = 2

In [31]:
npoints = 1000000

In [32]:
points = np.random.rand(npoints,ndim)

In [33]:
points[0:2,:]

array([[0.28223211, 0.73565923],
       [0.3084483 , 0.18954866]])

In [41]:
dfo = np.zeros((npoints,1))
op=0

In [35]:
%%time
for i in range(npoints):
    for j in range(0,ndim):
        dfo[i]  = dfo[i] + math.pow(points[i,j],2)
    dfo[i] = np.sqrt(dfo[i])
    if (dfo[i]>1):
        op +=1


Wall time: 7.91 s


In [36]:
print("Fraction of points outside qudrant is ", op/npoints) 

Fraction of points outside qudrant is  0.214295


In [57]:
%%time
sq_points = points*points
dfo = np.sqrt(np.sum(sq_points, axis=1))
op = np.sum(dfo>1)
#Easier way lol

Wall time: 49 ms


In [58]:
print("Fraction of points outside qudrant is ", op/npoints) 

Fraction of points outside qudrant is  0.214295


In [70]:
%%time
op = np.sum(np.sqrt(np.sum(points*points, axis=1))>1)

Wall time: 44 ms


In [67]:
print("Fraction of points outside qudrant is ", op/npoints) 

Fraction of points outside qudrant is  0.214295


In [4]:
def area_outside(npoints, ndim):
    points = np.random.rand(npoints,ndim)
    return (np.sum(np.sqrt(np.sum(points*points, axis=1)>1)))/npoints

In [5]:
area_outside(100,2)

0.16

In [6]:
area_outside(100000,2)

0.21344

In [7]:
for i in range(2,11):
    print (i, area_outside(100000,i))

2 0.2144
3 0.47552
4 inf
5 inf
6 inf
7 inf
8 inf
9 inf
10 inf


### Broadcasting

In [3]:
arr1 = np.arange(6)

In [4]:
arr1.shape

(6,)

In [8]:
arr1 = arr1.reshape(3,2)

In [9]:
arr1, arr1.shape

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 (3, 2))

In [10]:
arr2 = np.arange(6).reshape(3,2)

In [11]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
arr1+arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
arr1 + arr2[0].reshape(1,2) #3x2 matrix + 1x2 matrix 

array([[0, 2],
       [2, 4],
       [4, 6]])

In [16]:
arr1 + arr2[:,0].reshape(3,1) #3x2 matrix + 3x1 matrix

array([[0, 1],
       [4, 5],
       [8, 9]])

In [17]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
 arr1 = np.arange(24).reshape((2,3,4))

In [19]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
arr2 = np.ones((1,4))

In [21]:
arr2

array([[1., 1., 1., 1.]])

In [22]:
arr1 + arr2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [23]:
arr1 = np.arange(4)

In [25]:
arr2 = np.arange(5)

In [26]:
arr1.shape, arr2.shape

((4,), (5,))

In [27]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [29]:
arr1.reshape((4,1))+arr2 #4x1 + 1x5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [2]:
arr = np.random.rand(3,3)

In [3]:
arr

array([[0.5775033 , 0.60204843, 0.0882501 ],
       [0.24582758, 0.01168296, 0.74395649],
       [0.0205417 , 0.53154228, 0.6030183 ]])

In [4]:
arr.T

array([[0.5775033 , 0.24582758, 0.0205417 ],
       [0.60204843, 0.01168296, 0.53154228],
       [0.0882501 , 0.74395649, 0.6030183 ]])

### File Handling

In [8]:
planets_small = np.loadtxt("C:/Users/apoor/Desktop/Programs/Python Programs/planets-small.txt", skiprows=1, usecols=(1,2,3,4,5,6,7,8,9))

In [9]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [10]:
planets_small.ndim, planets_small.shape

(2, (3, 9))

In [11]:
planets = np.loadtxt("C:/Users/apoor/Desktop/Programs/Python Programs/planets.txt", skiprows=1, usecols=(1,2,3,4,5,6,7,8,9))

ValueError: could not convert string to float: 'Unknown'

In [12]:
planets = np.genfromtxt("C:/Users/apoor/Desktop/Programs/Python Programs/planets.txt",skip_header=1, usecols=(1,2,3,4,5,6,7,8,9))

In [13]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [14]:
planets.shape

(20, 9)

In [17]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [18]:
 planets_new = np.nan_to_num(planets,-1)

In [19]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [21]:
 np.savetxt("C:/Users/apoor/Desktop/Programs/Python Programs/planets-new.txt", planets_new, delimiter=", ")

In [22]:
np.save("C:/Users/apoor/Desktop/Programs/Python Programs/planetsnew", planets_new)

In [24]:
arr1 = np.random.rand(1000,10)
arr2 = np.random.rand(2000,5)
arr3 = np.random.rand(20,10000)

In [25]:
np.savez("C:/Users/apoor/Desktop/Programs/Python Programs/many_arrs", arr1,arr2,arr3)

In [26]:
arrs = np.load("C:/Users/apoor/Desktop/Programs/Python Programs/many_arrs.npz")

In [27]:
type(arrs)

numpy.lib.npyio.NpzFile

In [28]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [30]:
arrs['arr_0'].shape

(1000, 10)

In [31]:
np.savez_compressed("C:/Users/apoor/Desktop/Programs/Python Programs/manyarr_comp", arr1,arr2,arr3)

In [32]:
arr1 = np.zeros((1000,1000))

In [33]:
np.savez("C:/Users/apoor/Desktop/Programs/Python Programs/zeroo",arr1)

In [36]:
np.savez_compressed("C:/Users/apoor/Desktop/Programs/Python Programs/zeroo_comp", arr1)

### Stats with Numpy

In [70]:
arr = np.random.rand(10000000,)

In [38]:
np.amin(arr)

5.020863684923604e-06

In [40]:
np.amax(arr)

0.9999978206043044

In [41]:
np.mean(arr)

0.5000424072260019

In [53]:
np.var(arr)

0.08379957249299023

In [55]:
np.std(arr)

0.2894815581224307

In [56]:
np.median(arr)

0.5001374837816897

In [57]:
np.percentile(arr,30)

0.29918142818043286

In [58]:
np.percentile(arr,90)

0.9002581843931262

In [71]:
%%time
iqr = np.percentile(arr,75) - np.percentile(arr,25)
#Iqr = q3 - q1 => 75th percentile - 50th percentile

Wall time: 382 ms


In [60]:
iqr


0.5042514474849051

In [61]:
quartiles =np.percentile(arr,[25,75])

In [62]:
quartiles

array([0.24823576, 0.75248721])

In [72]:
%%time
quartiles =np.percentile(arr,[25,75])
iqr = quartiles[1]-quartiles[0]

Wall time: 263 ms


In [66]:
iqr

0.5042514474849051

In [73]:
(arr-np.mean(arr))/np.std(arr) #z score

array([ 0.22853274, -0.75397593, -0.48605953, ...,  1.4319222 ,
       -0.81750139, -0.2207184 ])

In [74]:
np.histogram(arr)

(array([ 999460,  999355, 1000984,  999282, 1001202, 1001399,  999112,
         999956,  999545,  999705], dtype=int64),
 array([1.77774721e-07, 1.00000158e-01, 2.00000137e-01, 3.00000117e-01,
        4.00000097e-01, 5.00000077e-01, 6.00000056e-01, 7.00000036e-01,
        8.00000016e-01, 8.99999996e-01, 9.99999975e-01]))

In [75]:
np.histogram(arr,bins= 5)

(array([1998815, 2000266, 2002601, 1999068, 1999250], dtype=int64),
 array([1.77774721e-07, 2.00000137e-01, 4.00000097e-01, 6.00000056e-01,
        8.00000016e-01, 9.99999975e-01]))

In [77]:
np.histogram(arr,bins=[0,0.25,0.5,0.75,1])

(array([2499308, 2500975, 2500900, 2498817], dtype=int64),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [78]:
bins=[0,0.25,0.5,0.75,1]

In [79]:
np.digitize(arr,bins)

array([3, 2, 2, ..., 4, 2, 2], dtype=int64)

In [88]:
arr1 =np.random.randint(1,10,(10,))

In [89]:
arr1

array([3, 7, 1, 1, 1, 8, 6, 3, 2, 8])

In [90]:
bins = [0,6,10]

In [91]:
np.digitize(arr1,bins)

array([1, 2, 1, 1, 1, 2, 2, 1, 1, 2], dtype=int64)

In [92]:
np.digitize(arr1,bins, right=True)

array([1, 2, 1, 1, 1, 2, 1, 1, 1, 2], dtype=int64)

In [93]:
arr1= np.random.randint(50,80,100) #weight

In [95]:
arr2 = np.random.randint(150,185,100) #height

In [97]:
arr3 = np.random.randint(18,22,100)#age

In [100]:
np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [102]:
arr2d = np.vstack((arr1,arr2,arr3))

In [103]:
arr2d.shape

(3, 100)

In [104]:
np.min(arr2d,axis=1)

array([ 50, 150,  18])

### Rules of stats

#### 1. Mean subtracted array has zero mean

In [10]:
arr = np.random.rand(1000)

In [11]:
mean = np.mean(arr)

In [12]:
arr1 = arr-mean

In [13]:
np.mean(arr1)

1.1546319456101627e-17

#### 2. Computing mean with a smaller set of values


In [14]:
arr = np.random.rand(1000)

In [18]:
for k in range(1,50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

1 0.8357729788387508
2 0.4896504267000113
3 0.4184601319244126
4 0.42555164437683446
5 0.4358445660410143
6 0.4459879101706341
7 0.4332472027877555
8 0.4705839087142031
9 0.47959390526445855
10 0.5025800744411775
11 0.5099841679021494
12 0.5438275601837504
13 0.5523387626012612
14 0.5659361276963338
15 0.5307619615746677
16 0.5373322722133996
17 0.5204477925926053
18 0.5077241326957663
19 0.48142480166749885
20 0.4893069406811746
21 0.5051329813566768
22 0.4887552743424004
23 0.5097304460044088
24 0.5013028630013371
25 0.5196369863565726
26 0.5165302608410544
27 0.5065486922567946
28 0.5094548231825021
29 0.5075850455389087
30 0.4979940893853475
31 0.5133038265588464
32 0.5085638150081297
33 0.5057526482717951
34 0.4961164065945598
35 0.5056802405758762
36 0.5080036797306221
37 0.5009950715624694
38 0.4929409212397764
39 0.4859401487452307
40 0.47489151433854887
41 0.4815507477501923
42 0.4799425427520362
43 0.4757249259605945
44 0.46752530903817574
45 0.4584001818688611
46 0.467617805

In [19]:
np.cumsum?

Signature: np.cumsum(a, axis=None, dtype=None, out=None)
Docstring:
Return the cumulative sum of the elements along a given axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    Axis along which the cumulative sum is computed. The default
    (None) is to compute the cumsum over the flattened array.
dtype : dtype, optional
    Type of the returned array and of the accumulator in which the
    elements are summed.  If `dtype` is not specified, it defaults
    to the dtype of `a`, unless `a` has an integer dtype with a
    precision less than that of the default platform integer.  In
    that case, the default platform integer is used.
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output
    but the type will be cast if necessary. See `ufuncs-output-type` for
    more details.

Returns
-------
cumsum_along_axis : ndarray.
    A new array holding the resul

In [22]:
mean_cum = np.cumsum(arr)/np.arange(1,1001)

In [23]:
mean_cum[0:50]

array([0.83577298, 0.48965043, 0.41846013, 0.42555164, 0.43584457,
       0.44598791, 0.4332472 , 0.47058391, 0.47959391, 0.50258007,
       0.50998417, 0.54382756, 0.55233876, 0.56593613, 0.53076196,
       0.53733227, 0.52044779, 0.50772413, 0.4814248 , 0.48930694,
       0.50513298, 0.48875527, 0.50973045, 0.50130286, 0.51963699,
       0.51653026, 0.50654869, 0.50945482, 0.50758505, 0.49799409,
       0.51330383, 0.50856382, 0.50575265, 0.49611641, 0.50568024,
       0.50800368, 0.50099507, 0.49294092, 0.48594015, 0.47489151,
       0.48155075, 0.47994254, 0.47572493, 0.46752531, 0.45840018,
       0.46761781, 0.46086547, 0.46603962, 0.46488769, 0.4615218 ])

### 3. Effect of outliers on mean and median

In [30]:
arr = np.random.randint(1,100,100)

In [31]:
np.mean(arr)

51.94

In [32]:
np.median(arr)

52.0

In [33]:
arr = np.append(arr, [1000,2000])

In [34]:
arr.shape

(102,)

In [35]:
np.mean(arr) #Sensitive to outliers

80.33333333333333

In [36]:
np.median(arr) #Not very sensitive to outliers

52.5

#### 3. Effect of scaling

In [37]:
arr = np.random.rand(100)

In [38]:
arr

array([0.63971718, 0.50755881, 0.75736564, 0.55088303, 0.83036627,
       0.6023159 , 0.28699838, 0.21989396, 0.52456152, 0.00362468,
       0.77321122, 0.5995344 , 0.62095704, 0.09331992, 0.60836431,
       0.54443705, 0.157797  , 0.18370924, 0.85692873, 0.41273396,
       0.53503299, 0.26486337, 0.62881707, 0.30691189, 0.87108953,
       0.24475685, 0.8364305 , 0.78429667, 0.23007036, 0.6734686 ,
       0.65993273, 0.32398955, 0.23280413, 0.48359341, 0.35869615,
       0.10508374, 0.10355177, 0.66830698, 0.97743508, 0.36562527,
       0.62284434, 0.36692113, 0.47076746, 0.97397239, 0.97271379,
       0.61940955, 0.20169573, 0.37185569, 0.74681543, 0.38900146,
       0.11701973, 0.52597966, 0.70887389, 0.89729666, 0.33788534,
       0.01165037, 0.60159207, 0.05714497, 0.9489826 , 0.48182479,
       0.19192102, 0.85208663, 0.07054374, 0.36548703, 0.96126239,
       0.7121547 , 0.69210951, 0.76773074, 0.98645032, 0.16275885,
       0.54692692, 0.08448191, 0.15218856, 0.55534071, 0.25521

In [40]:
np.mean(arr)

0.4804262573681401

In [41]:
np.median(arr)

0.5160601621183059

In [43]:
arr1 = 2.5 * arr + 0.7

In [45]:
np.mean(arr1), 2.5 * np.mean(arr) + 0.7

(1.90106564342035, 1.9010656434203501)

In [46]:
np.median(arr1), 2.5 * np.median(arr) + 0.7

(1.9901504052957644, 1.9901504052957646)

In [48]:
np.var(arr1), 2.5 * np.var(arr) + 0.7, 2.5 * 2.5 * np.var(arr)

(0.4504629860206, 0.88018519440824, 0.45046298602059986)

In [49]:
np.std(arr1), 2.5 * np.std(arr) + 0.7, 2.5 * np.std(arr)

(0.6711653939384836, 1.3711653939384836, 0.6711653939384836)

In [50]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [54]:
np.mean((0.21 * arr1 - 0.75 * arr2)), ((0.21 * np.mean(arr1)) - (0.75 * np.mean(arr2)))

(-0.2808663317049484, -0.28086633170494835)

#### Problems


1. Mean, median,iqr for ST, RD, I 
2. Histogram of ST with 10 bins
3. Mean of ST grouped by 25. 
4. Mean of ST where he has scored a century
5. Mean of ST where RD's score is less than 10
6. Mean of ST based on quartile of I's scores
7. Max score for each match
8. How many more runs Sachin scores on average after having scored x runs   
9.How many matches did ST take to score 1000 runs, next 1000, etc


In [58]:
runs = np.genfromtxt("C:/Users/apoor/Desktop/Programs/Python Programs/cric-data.tsv",skip_header=1, usecols=(1,2,3)).T


In [59]:
runs

array([[100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
          4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
        138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
          1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
        146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
          6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
         14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
         32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
          4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
         26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
          0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
         69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
         34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
         93.,  35.,  63.,  74.,   8., 

In [60]:
runs.shape

(3, 225)

In [92]:
sachin = runs[0]
rahul =runs[1]
india = runs[2]

1. 

In [61]:
sachin_mean  = np.mean(runs[0])

In [62]:
sachin_mean

39.87555555555556

In [70]:
sachin_median = np.median(runs[0])

In [71]:
sachin_median

27.0

In [72]:
sachin_iqr = np.percentile(runs[0], 75) - np.percentile(runs[0], 25) 

In [73]:
sachin_iqr

57.0

In [63]:
rahul_mean = np.mean(runs[1])

In [65]:
rahul_mean

32.062222222222225

In [76]:
rahul_median = np.median(runs[1])

In [77]:
rahul_median

22.0

In [78]:
rahul_iqr = np.percentile(runs[1], 75) - np.percentile(runs[1], 25) 

In [79]:
rahul_iqr

46.0

In [66]:
india_mean = np.mean(runs[2])

In [67]:
india_mean

220.79555555555555

In [81]:
india_median = np.median(runs[2])
india_median

216.0

In [82]:
india_iqr = np.percentile(runs[2], 75) - np.percentile(runs[2], 25) 
india_iqr

98.0

In [84]:
#More efficient
def stats(p):
    print(" Mean: ",np.mean(p),"\n Median: ", np.median(p))
    print(" IQR: ", np.percentile(p, 75) - np.percentile(p, 25))

In [91]:
sachins = stats(runs[0])
rahuls = stats(runs[1])
indias = stats(runs[2])

 Mean:  39.87555555555556 
 Median:  27.0
 IQR:  57.0
 Mean:  32.062222222222225 
 Median:  22.0
 IQR:  46.0
 Mean:  220.79555555555555 
 Median:  216.0
 IQR:  98.0


In [89]:
#Most efficient
print("Mean: ", np.mean(runs, axis = 1))
print("Median: ",np.median(runs,axis=1))
print("IQR: ", np.percentile(runs,75,axis=1)-np.percentile(runs,25,axis=1))

Mean:  [ 39.87555556  32.06222222 220.79555556]
Median:  [ 27.  22. 216.]
IQR:  [57. 46. 98.]


2.

In [68]:
sachin_histogram = np.histogram(runs[0], bins=10) #By default also takes bin size as 10

In [69]:
sachin_histogram

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

3.

In [93]:
sachin.shape

(225,)

In [98]:
np.mean(sachin.reshape(9,25), axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

4. and 5.

In [101]:
np.mean(sachin[sachin>=100])

125.0

In [105]:
np.mean(sachin[rahul<=10])

40.2112676056338

6. 

In [108]:
india_quartiles = np.percentile(india, [25,50,75,100])

#If India <= 175, calc ST average
#If India <= 216, calc ST average
#If India <= 273, calc ST average
#If India <= 499, calc ST average

In [112]:
india_quartiles = india_quartiles.reshape(4,1)

In [113]:
indices = india < india_quartiles

In [114]:
indices.shape

(4, 225)

In [119]:
sachin[indices[0,:]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [121]:
for i in range(4):
    print (i+1, np.mean(sachin[indices[i,:]]))

1 19.672727272727272
2 28.18018018018018
3 31.688622754491018
4 39.799107142857146


7.

In [124]:
match = runs[0:2,:].T

In [130]:
who_higher = match.argmax(axis=1)

In [131]:
np.where(who_higher==0, "Sachin", "Rahul")

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

8. 

In [133]:
x_arr = np.arange(0,101,5)

In [139]:
x_arr = x_arr.reshape(x_arr.shape[0],1)

In [140]:
indices = sachin >= x_arr

In [141]:
indices.shape

(21, 225)

In [144]:
for i in range(x_arr.shape[0]):
    print(x_arr[i,0], np.mean(sachin[indices[i,:]] - x_arr[i,0]))

0 39.87555555555556
5 45.61363636363637
10 47.48026315789474
15 47.45255474452555
20 46.824
25 44.10084033613445
30 45.13461538461539
35 43.24742268041237
40 44.05882352941177
45 43.41558441558441
50 43.98529411764706
55 42.317460317460316
60 38.67213114754098
65 37.654545454545456
70 37.08163265306123
75 34.34782608695652
80 30.75
85 28.65
90 27.4
95 26.433333333333334
100 25.0


9. 

In [146]:
np.histogram(np.cumsum(sachin), bins = np.arange(0,10000,1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30], dtype=int64),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))

## Test

In [147]:
a = np.array([10,12,1,5])
a = a/0.0
print(a[0])

inf


In [148]:
a = np.array([1,2,3,4,5])
print(a[2:None])

[3 4 5]


In [149]:
a = np.array[[1,2,3,],[4,5,6]]
print(a[1][2])

TypeError: 'builtin_function_or_method' object is not subscriptable